services:
  - type: web
    name: picture-perfect-tv-install
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_EMAIL
        value: pptvinstall@gmail.com
      - key: EMAIL_FROM
        value: Picture Perfect TV Install <pptvinstall@gmail.com>
      - key: GMAIL_USER
        value: pptvinstall@gmail.com
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: picture-perfect-tv-db
          property: connectionString
  
  - type: pserv
    name: picture-perfect-tv-db
    env: postgresql
    plan: free
    databaseName: picture_perfect_tv
    databaseUser: admin